name: build-page
run-name: Build Page
on:
  push:
    branches:
      - main

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: yarn install

      - run: yarn export

      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}