name: Remove link from site
on:
    workflow_dispatch:
        inputs:
            short:
                description: "The short slug of the redirect to remove."
                required: true

jobs:
    modify-links:
        runs-on: ubuntu-latest
        outputs:
            commit-sha: ${{ steps.push-changes.outputs.commit_long_sha }}
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"

            - name: Install packages
              run: yarn install

            - run: yarn linker remove ${{ github.event.inputs.short }}

            - name: Push changes
              id: push-changes
              uses: EndBug/add-and-commit@v9
              with:
                  message: 'remove "${{ github.event.inputs.short }}" link'

    generate-site:
        needs: modify-links
        uses: ./.github/workflows/generate-site.yml
        with:
            commit-sha: ${{ needs.modify-links.outputs.commit-sha }}
